// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJtwOgmUfAWuWrs02AZYDKmD8nglaPHeU',
    appId: '1:1059832218486:web:7d60c16d54f5ad10787057',
    messagingSenderId: '1059832218486',
    projectId: 'virtualbuild-6307d',
    authDomain: 'virtualbuild-6307d.firebaseapp.com',
    storageBucket: 'virtualbuild-6307d.appspot.com',
    measurementId: 'G-YRDN59G8GP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlN1ReOYQzrHPsvYqx0cHb3IZcyvrb7K8',
    appId: '1:1059832218486:android:c06a0ae4d28f43fc787057',
    messagingSenderId: '1059832218486',
    projectId: 'virtualbuild-6307d',
    storageBucket: 'virtualbuild-6307d.appspot.com',
  );
}
